create table if not exists book
(
    id bigint generated by default as identity (maxvalue 2147483647)
    constraint book_pkey
    primary key,
    author varchar(255) not null,
    description text not null,
    image varchar(255) not null,
    isbn varchar(255) not null,
    print_year bigint not null,
    read_already boolean not null,
    title varchar(255) not null
    );

alter table book owner to postgres;

create table if not exists stats
(
    id bigint generated by default as identity
    constraint stats_pkey
    primary key,
    count integer,
    local_date varchar(255),
    book_id bigint
    constraint fkxqdibm1bvxax4so2a9b8kndu
    references book
    );

alter table stats owner to postgres;