arch: amd64
os: linux
dist: focal
language: java
jdk: opendjk-11

services:
- docker

cache:
  directories:
  - $HOME/.m2

script:
- ./mvnw clean install -B

deploy:
  provider: heroku
  app: books-service-api
  api_key:
    secure: 8a180d79-b8ed-44b7-99ff-c9711ac87aed