arch: amd64
os: linux
dist: focal
language: java
jdk: 
  - opendjk11
  - oraclejdk11

services:
  - docker
  - postgresql

env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=postgres


cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c 'create database travis_ci_test' -U postgres

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

script:
  - ./mvnw clean install -DskipTests=true -B

after_success:

deploy:
  provider: heroku
  app: books-service-api
  api_key:
    secure: "8a180d79-b8ed-44b7-99ff-c9711ac87aed"