arch: amd64
os: linux
dist: focal
language: java
jdk: 
  - oraclejdk11

services:
  - docker
  - postgresql

env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=postgres


cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c 'create database books_service_db' -U postgres

script:
  - ./mvnw clean install -DskipTests=true -B

after_success:

deploy:
  provider: heroku
  app: books-service-api
  api_key:
    secure: "8a180d79-b8ed-44b7-99ff-c9711ac87aed"