arch: amd64
os: linux
dist: focal
language: java
jdk: 
  - opendjk11
  - oraclejdk11

services:
  - docker
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=postgres


cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean install -DskipTests=true -B
  - docker-compose -f docker-compose.yml up --build


deploy:
  provider: heroku
  app: books-service-api
  api_key:
    secure: "8a180d79-b8ed-44b7-99ff-c9711ac87aed"